# Generated by Django 5.2.6 on 2025-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', 'User logged in'), ('logout', 'User logged out'), ('add', 'Added record'), ('edit', 'Edited record'), ('delete', 'Deleted record'), ('pos', 'POS transaction'), ('other', 'Other')], max_length=20),
        ),
    ]
