# Generated by Django 5.2.6 on 2025-10-08 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.CreateModel(
            name='RestockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField(verbose_name='Quantity Added')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Restocked')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='Inventory.item')),
            ],
        ),
    ]
