# Generated by Django 5.2.8 on 2025-11-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_item_category_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_stock_level',
            field=models.IntegerField(default=10, verbose_name='Minimum Stock Level'),
        ),
    ]
