# Generated by Django 5.2.6 on 2025-10-16 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_alter_sale_payment_method_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sale Item Unit (Daily Summary)',
                'verbose_name_plural': 'Sale Item Units (Daily Summaries)',
                'ordering': ['-date', '-total_quantity'],
            },
        ),
    ]
