# Generated by Django 5.2.6 on 2025-10-21 10:29

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_saleitem_product_name_alter_saleitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Daily Sales Record',
                'verbose_name_plural': 'Daily Sales Records',
                'ordering': ['-date'],
            },
        ),
    ]
