# Generated by Django 5.2.8 on 2025-11-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_item_category_alter_item_created_at_and_more'),
        ('POS', '0005_dailysalesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesrecord',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.item'),
        ),
    ]
