# Generated by Django 5.2.8 on 2025-11-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_alter_item_category_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='xgb.XGBRegressor', max_length=255)),
                ('train_start', models.DateField(blank=True, null=True)),
                ('train_end', models.DateField(blank=True, null=True)),
                ('horizon', models.PositiveIntegerField(default=7)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('artifact_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual', models.FloatField(blank=True, null=True)),
                ('predicted', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.item')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Sales_forecast.forecastrun')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='Sales_forec_date_fceb8c_idx')],
            },
        ),
    ]
